# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1
      
      - name: Change into working directory
        run: cd $GITHUB_WORKSPACE

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore NuGet packages
        run: nuget.exe restore Amethyst-Installer.sln

      - name: Initialize submodules
        run: git submodule update --init --recursive
      
      - name: Build
        run: MSBuild.exe "/p:Configuration=Dist;Platform=x64"
      
      - name: Get short SHA
        id: slug
        run: "$slug = 'slug=' + $env:GITHUB_SHA.SubString(0,7); echo $slug >> $GITHUB_STATE"
        
      - name: Rename distribution executable
        run: mv bin/x64/Dist/Amethyst-Installer/Amethyst-Installer.exe bin/x64/Dist/Amethyst-Installer/Amethyst-Installer-${{ env.slug }}.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Amethyst-Installer-${{ env.slug }}.exe
          path: bin/x64/Dist/Amethyst-Installer/Amethyst-Installer-${{ env.slug }}.exe
          if-no-files-found: error
